### ISSUE TITLE
Please make a telegram translate bot

### ISSUE THREAD

**Issue by telegrambotdev** [eidoriantan/messenger-translator#84]
Telegram is one if the mostly using im..it hugly support bots.so please make a code for telegram translate bot

Thank you

**Comment by eidoriantan** [comment]
This is not easy because I never used Telegram before. It sounds interesting so I'll create an account and use it for a while. I also have to read their documentations so this might take a while. I'll let you know when I finished it.

I'll close this issue for now since it is unrelated to this repository.

**Comment by eidoriantan** [comment]
Hey @telegrambotdev, I already finished a translator bot for Telegram. Here's the [Telegram link](https://t.me/msgr_translator_bot), and here's the [repository link](https://github.com/eidoriantan/messenger-translator-telegram)

**Comment by telegrambotdev** [comment]
Thanks bro
